### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by SonOfLilit** [manoss96/pregex#1]
Welcome to the burgeoning field of trying to make regex human-friendly! We're always happy to have more people working on this gnarly problem.

Here is a list of some other attempts:
https://github.com/SonOfLilit/kleenexp#similar-works

May I invite you to have a look at mine in particular and maybe join hands? We're already in quite an advanced stage, having just launched a `vscode` extension that allows using our syntax almost natively in your text editor.

Cheers,
Aur

**Comment by manoss96** [comment]
> Welcome to the burgeoning field of trying to make regex human-friendly! We're always happy to have more people working on this gnarly problem.
> 
> Here is a list of some other attempts: https://github.com/SonOfLilit/kleenexp#similar-works
> 
> May I invite you to have a look at mine in particular and maybe join hands? We're already in quite an advanced stage, having just launched a `vscode` extension that allows using our syntax almost natively in your text editor.
> 
> Cheers, Aur

Hey there! I've taken a look at your project and it looks pretty cool. Unfortunately I can't get myself into another project due to having to balance having a regular job as well as being involved in some other private projects too. You're more than welcome to play around with pregex though and raise an issue if you encounter some bug or even open a PR with a proposed solution. I've yet to create a "CONTRIBUTING" file but I'm planning on it!
