### ISSUE TITLE
pre = EnclosedBy(pre, Whitespace())  makes an error

### ISSUE THREAD

**Issue by hcchengithub** [manoss96/pregex#25]
In this example:
```
pre = Pregex('a')
pre = EnclosedBy(pre, Whitespace()) 
```
what I want is : `(?<=\s)a(?=\s)` but an error occored : "NonFixedWidthPatternException: Instances of class "Pregex" cannot receive an instance of class "Whitespace" in place of a lookbehind-restriction-pattern as the latter represents a pattern whose width is not fixed.". So where did I do wrong and how to fix it? 
Thank you very much !!

**Comment by manoss96** [comment]
``pregex.meta.essentials.Whitespace`` does not represent RegEx pattern ``\s``, that would be ``pregex.core.classes.AnyWhitespace``. The reason you're getting this error is because ``Whitespace`` represents a pattern that is able to match any string containing whitespace of any length. This pattern does not have a fixed width, and as such, it cannot be used as a lookbehind assertion pattern due to the Python's built in re module.

**Comment by hcchengithub** [comment]
Thank you very much! Now I am sure this library should be included in the standard!
